export const ADD_RECIPE = 'ADD_RECIPE'
export const GET_RECIPE = 'GET_RECIPE'
export const GET_RECIPES = 'GET_RECIPES'

export const ADD_INGREDIENT = 'ADD_INGREDIENT' 

export const GET_INGREDIENT_REQUEST = 'GET_INGREDIENT_REQUEST'
export const GET_INGREDIENT_SUCCESS = 'GET_INGREDIENT_SUCCESS'
export const GET_INGREDIENT_ERROR = 'GET_INGREDIENT_ERROR'


export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

export const GET_PROFILES_REQUEST = 'GET_PROFILES_REQUEST'
export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS'
export const GET_PROFILES_ERROR = 'GET_PROFILES_ERROR'

export const GET_USER_POSTS_REQUEST = 'GET_USER_POSTS_REQUEST'
export const GET_USER_POSTS_SUCCESS = 'GET_USER_POSTS_SUCCESS'
export const GET_USER_POSTS_ERROR = 'GET_USER_POSTS_ERROR'

export const ADD_POST_TO_PROFILE_REQUEST = 'ADD_POST_TO_PROFILE_REQUEST'
export const ADD_POST_TO_PROFILE_SUCCESS = 'ADD_POST_TO_PROFILE_SUCCESS'
export const ADD_POST_TO_PROFILE_ERROR = 'ADD_POST_TO_PROFILE_ERROR'

export const GET_FRIENDS_REQUEST = 'GET_FRIENDS_REQUEST'
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS'
export const GET_FRIENDS_ERROR = 'GET_FRIENDS_ERROR'

export const GET_FRIEND_LITTLE_INFROMATIONS_REQUEST = 'GET_FRIEND_LITTLE_INFROMATIONS_REQUEST'
export const GET_FRIEND_LITTLE_INFROMATIONS_SUCCESS = 'GET_FRIEND_LITTLE_INFROMATIONS_SUCCESS'
export const GET_FRIEND_LITTLE_INFROMATIONS_ERROR = 'GET_FRIEND_LITTLE_INFROMATIONS_ERROR'
export const CLEAR_FRIEND_LITTLE_INFROMATIONS = 'CLEAR_FRIEND_LITTLE_INFROMATIONS'

export const GET_FRIEND_REQUEST = 'GET_FRIEND_REQUEST'
export const GET_FRIEND_SUCCESS = 'GET_FRIEND_SUCCESS'
export const GET_FRIEND_ERROR = 'GET_FRIEND_ERROR'

export const GET_FRIEND_MESSAGES_REQUEST = 'GET_FRIEND_MESSAGES_REQUEST'
export const GET_FRIEND_MESSAGES_SUCCESS = 'GET_FRIEND_MESSAGES_SUCCESS'
export const GET_FRIEND_MESSAGES_ERROR = 'GET_FRIEND_MESSAGES_ERROR'


export const ADD_MESSAGE_TO_FRIEND_REQUEST = 'ADD_MESSAGE_TO_FRIEND_REQUEST'
export const ADD_MESSAGE_TO_FRIEND_SUCCESS = 'ADD_MESSAGE_TO_FRIEND_SUCCESS'
export const ADD_MESSAGE_TO_FRIEND_ERROR = 'ADD_MESSAGE_TO_FRIEND_ERROR'

export const LOGIN_CHECK = 'LOGIN_CHECK'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'
