export const ADD_RECIPE = 'ADD_RECIPE'
export const GET_RECIPE = 'GET_RECIPE'
export const GET_RECIPES = 'GET_RECIPES'

export const ADD_INGREDIENT = 'ADD_INGREDIENT' 

export const GET_INGREDIENT_REQUEST = 'GET_INGREDIENT_REQUEST'
export const GET_INGREDIENT_SUCCESS = 'GET_INGREDIENT_SUCCESS'
export const GET_INGREDIENT_ERROR = 'GET_INGREDIENT_ERROR'


export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST'
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS'
export const GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'

export const ADD_POST_TO_PROFILE = 'ADD_POST_TO_PROFILE'
export const UPDATE_POST_TITLE_INTO_PROFILE = 'UPDATE_POST_TITLE_INTO_PROFILE'
export const UPDATE_POST_BODY_INTO_PROFILE = 'UPDATE_POST_BODY_INTO_PROFILE'

export const ADD_MESSAGE_TO_FRIEND = 'ADD_MESSAGE_TO_FRIEND'
export const UPDATE_MESSAGE_TO_FRIEND = 'UPDATE_MESSAGE_TO_FRIEND'